FROM balenalib/%%BALENA_ARCH%%-debian:bullseye-run

RUN apt-get update && apt-get install -yq \
    docker.io \
    docker-compose \
    module-init-tools && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# configure the docker daemon
COPY overlay2-daemon.json /etc/docker/daemon.json

COPY start.sh .

CMD ["bash", "start.sh"]