# Dummy: No idf for aarch64 - https://github.com/espressif/esp-idf/issues/6432
# remove this file once idf is available for aarch64 (use Dockerfile.template)

FROM balenalib/%%BALENA_MACHINE_NAME%%-debian:buster-run

ARG DEBIAN_FRONTEND=noninteractive

ENV HOME=/home/iot
WORKDIR /home/iot

COPY ./start.sh /usr/local/bin/start.sh

CMD [ "/bin/bash", "/usr/local/bin/start.sh" ]
