# https://github.com/home-assistant/docker/blob/master/Dockerfile

# FROM homeassistant/home-assistant:stable
FROM esphome/esphome

COPY conf /usr/local/bin

CMD [ "/bin/bash", "/usr/local/bin/start.sh" ]