FROM balenalib/%%BALENA_ARCH%%-alpine

RUN apk update \
 && apk add --no-cache \
    bash \
    jq \
    nano \
    rsync

COPY conf /usr/local/src/config
COPY start.sh /usr/local/bin

CMD [ "/bin/bash", "/usr/local/bin/start.sh" ]
