name: Jupyter Stacks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # JOB to run change detection
  changes:
    runs-on: ubuntu-latest
    outputs:
      # Expose matched files output variable
      docker: ${{ steps.filter.outputs.docker }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3 
    - name: Find changed files
      uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          docker:
            - "jupyter/**"

  # JOB to build and test each of modified dockerfiles
  build:
    needs: changes
    if: ${{ needs.changes.outputs.docker == 'true' }}
    strategy:
      matrix:
        # add addional base images as desired
        base: [ "base-notebook", "scipy-notebook" ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Environment
        run: |
          date="$(date "+%Y-%m-%d")"
          echo "date=$date" >> $GITHUB_ENV
      - name: Login to Docker Hub
        uses: docker/login-action@v2  
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
        with:
          context: jupyter
          build-args: 
            BASE=jupyter/${{ matrix.base }}
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/${{ matrix.base }}:latest,
            ${{ secrets.DOCKER_HUB_USERNAME }}/${{ matrix.base }}:${{ env.date }}
          platforms: linux/amd64,linux/arm64
          push: true